apiVersion: v1
kind: Service
metadata:
  labels:
    name: miq-app
  name: miq-app 
spec:
  ports:
    - port: 80
      targetPort: 80
      name: miq-app-http
    - port: 443
      targetPort: 443
      name: miq-app-ssl
  selector:
    name: miq-app
