apiVersion: v1
kind: Pod
metadata:
  name: mattermost
  labels:
    name: mattermost
spec:
  containers:
    - image: $image
      name: mattermost
      env:
        - name: DRIVER_NAME
          value: ${DRIVER_NAME}
        - name: DATABASE_SERVICE_NAME
          value: ${DATABASE_SERVICE_NAME}
        - name: MYSQL_USER
          value: ${MYSQL_USER}
        - name: MYSQL_PASSWORD
          value: ${MYSQL_PASSWORD}
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
      ports:
        - name: mattermost
          containerPort: $hostport
          
