apiVersion: v1
kind: Pod
metadata:
  name: miq-memcached
  labels:
    name: miq-memcached
spec:
  containers:
    - name: miq-memcached
      image: docker.io/fbladilo/miq-memcached
      env:
              - name: MEMCACHED_MAX_MEMORY
                value: '$MEMCACHED_MAX_MEMORY'
              - name: MEMCACHED_MAX_CONNECTIONS
                value: '$MEMCACHED_MAX_CONNECTIONS'
              - name: MEMCACHED_SLAB_PAGE_SIZE
                value: $MEMCACHED_SLAB_PAGE_SIZE
      ports:
        - containerPort: 11211
          name: miq-memcached
