apiVersion: v1
kind: Pod
metadata:
  name: miq-postgresql
  labels:
    name: miq-postgresql
spec:
  containers:
    - image: docker.io/fbladilo/miq-postgresql
      name: miq-postgresql
      env:
              - name: POSTGRESQL_USER
                value: $POSTGRESQL_USER
              - name: POSTGRESQL_PASSWORD
                value: $POSTGRESQL_PASSWORD
              - name: POSTGRESQL_DATABASE
                value: $POSTGRESQL_DATABASE
      ports:
        - containerPort: 5432
          name: miq-postgresql
      volumeMounts:
        - name: miq-postgresql-persistent-storage
          mountPath: /var/lib/pgsql/data
  volumes:
    - name: miq-postgresql-persistent-storage
      persistentVolumeClaim:
       claimName: miq-postgresql-claim
