---
apiVersion: v1
kind: Service
metadata:
  name: etherpad-svc
  labels:
    name: etherpad-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: etherpad-server
  selector:
    name: etherpad
