apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  containers:
    - name: postgresql
      image: centos/postgresql-95-centos7
      env:
        - name: POSTGRESQL_DATABASE
          value: $db_name
        - name: POSTGRESQL_USER
          value: $db_user
        - name: POSTGRESQL_PASSWORD
          value: $dp_pass
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/pgsql/data
  volumes:
    - name: postgresql-persistent-storage
      persistentVolumeClaim:
       claimName: postgresql-claim
